apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: rhacm-policies
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values: 
        - "dev"